name: Code linter

on:
  workflow_run:
    workflows: ["Build image"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image from GitHub Container Registry
        run: docker pull ghcr.io/${{ github.repository }}/django-boiler:latest

      - name: Run command inside Docker image
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/django-boiler:latest sh scripts/clean_code.sh
