name: Build image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-django-boiler
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image with caching
        run: |
          # Initialize cache directory if it doesn't exist
          mkdir -p /tmp/.buildx-cache

          # Build and push Docker image with cache
          docker buildx build \
            --file ./Dockerfile \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            -t ghcr.io/${{ github.repository }}/django-boiler:latest \
            --load .

  clean-code:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # - name: Pull Docker image from GitHub Container Registry
      #   run: docker pull ghcr.io/${{ github.repository }}/django-boiler:latest

      - name: Run command inside Docker image
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/django-boiler:latest sh scripts/clean_code.sh