name: Build image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Generate cache key
        id: cache-key
        run: echo "key=${{ runner.os }}-buildx-django-boiler-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-buildx-django-boiler-

      - name: Build Docker image with cache and export to tar
        run: |
          mkdir -p /tmp/.buildx-cache
          mkdir docker-image/

          docker buildx build \
            --file ./Dockerfile \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --output type=docker,dest=docker-image/django-boiler.tar \
            -t ghcr.io/${{ github.repository }}/django-boiler:latest \
            .

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: django-boiler-image
          path: docker-image/django-boiler.tar

  clean-code:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: django-boiler-image
          path: ./docker-image

      - name: Load Docker image from tarball
        run: docker load -i ./docker-image/django-boiler.tar

      - name: Run command inside Docker image
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/django-boiler:latest sh scripts/clean_code.sh

  publish-image:
    runs-on: ubuntu-latest
    needs: clean-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: django-boiler-image
          path: ./docker-image

      - name: Load Docker image from tarball
        run: docker load -i ./docker-image/django-boiler.tar

      - name: Publish image
        run: |
          docker push ghcr.io/${{ github.repository }}/django-boiler:latest
          docker push ghcr.io/${{ github.repository }}/django-boiler:${{ github.sha }}
